#!/bin/bash
# apply_schem_diff.sh
#
# This script applies a schema diff file (such as diff.sql generated by apgdiff)
# to a Postgres database running in a Docker container.
#
# It auto-detects the running Postgres container:
#   - If the container name contains "devcontainer", the target database is "wanderer_dev".
#   - Otherwise, the target database is "postgres".
#
# Usage:
#   ./apply_schema_diff.sh diff.sql
#
# IMPORTANT: It is recommended that you backup your current schema before applying the diff.
#

set -e  # Exit immediately if any command fails

# Check that a diff file is provided.
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <diff_file.sql>"
    exit 1
fi

DIFF_FILE="$1"

if [ ! -f "$DIFF_FILE" ]; then
    echo "Error: Diff file '$DIFF_FILE' not found."
    exit 1
fi

# Define possible Postgres container names.
POSSIBLE_CONTAINERS=("wanderer-wanderer_db-1" "wanderer_devcontainer-db-1")
CONTAINER_NAME=""

echo "Detecting running Postgres container..."
for container in "${POSSIBLE_CONTAINERS[@]}"; do
    if docker inspect "$container" > /dev/null 2>&1; then
        CONTAINER_NAME="$container"
        break
    fi
done

if [ -z "$CONTAINER_NAME" ]; then
    echo "Error: No known Postgres container found. Checked: ${POSSIBLE_CONTAINERS[*]}"
    exit 1
fi

echo "Using database container: $CONTAINER_NAME"

# Set database user and determine target database based on container name.
DB_USER="postgres"
if [[ "$CONTAINER_NAME" == *"devcontainer"* ]]; then
    DB_NAME="wanderer_dev"
else
    DB_NAME="postgres"
fi

echo "Target database: $DB_NAME"
echo ""

# OPTIONAL: Backup current schema before applying the diff.
SCHEMA_BACKUP="current_schema_$(date +'%Y%m%d_%H%M%S').sql"
echo "Backing up current schema to $SCHEMA_BACKUP..."
docker exec -i "$CONTAINER_NAME" pg_dump -U "$DB_USER" -d "$DB_NAME" --schema-only --no-owner --no-acl > "$SCHEMA_BACKUP"
echo "Current schema backup complete."
echo ""

# Apply the schema diff.
echo "Applying schema diff from file: $DIFF_FILE..."
docker exec -i "$CONTAINER_NAME" psql -U "$DB_USER" -d "$DB_NAME" < "$DIFF_FILE"
echo "Schema diff applied successfully."

