services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - db-new:/var/lib/postgresql/data

  wanderer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 4444
      DB_HOST: db
      WEB_APP_URL: "http://localhost:4444"
      ERL_AFLAGS: "-kernel shell_history enabled"
    ports:
      - 4444:4444
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ..:/app:delegated
      - command-history:/commandhistory
    command: sleep infinity

volumes:
  db-new: {}
  command-history: {}
