defmodule WandererApp.Repo.Migrations.AddZooCustomAgain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`.
  Modified to be idempotent by using raw SQL.
  """

  use Ecto.Migration

  def up do
    execute("ALTER TABLE map_system_v1 ADD COLUMN IF NOT EXISTS owner_id text")
    execute("ALTER TABLE map_system_v1 ADD COLUMN IF NOT EXISTS owner_type text")
  end

  def down do
    execute("ALTER TABLE map_system_v1 DROP COLUMN IF EXISTS owner_type")
    execute("ALTER TABLE map_system_v1 DROP COLUMN IF EXISTS owner_id")
  end
end
