defmodule WandererApp.Repo.Migrations.AddZooFlags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("ALTER TABLE map_system_v1 ADD COLUMN IF NOT EXISTS custom_flags text")
  end

  def down do
    execute("ALTER TABLE map_system_v1 DROP COLUMN IF EXISTS custom_flags")
  end
end
