defmodule WandererApp.Repo.Migrations.AddFleetReadinessReadyCharacters do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'map_user_settings_v1'
        AND column_name = 'ready_characters'
      ) THEN
        ALTER TABLE map_user_settings_v1
        ADD COLUMN ready_characters text[] DEFAULT '{}';
      END IF;
    END $$;
    """)
  end

  def down do
    execute("ALTER TABLE map_user_settings_v1 DROP COLUMN IF EXISTS ready_characters")
  end
end
