defmodule WandererApp.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("user_activity_v1", "user_activity_v1_pkey")

    alter table(:user_activity_v1) do
      modify :user_id, :uuid, primary_key: false
    end

    create index(:map_chain_passages_v1, [:inserted_at])

    create index(:map_chain_passages_v1, [
             :map_id,
             :solar_system_source_id,
             :solar_system_target_id
           ])

    create index(:map_chain_passages_v1, [:map_id, :character_id])
  end

  def down do
    drop_if_exists index(:map_chain_passages_v1, [:map_id, :character_id])

    drop_if_exists index(:map_chain_passages_v1, [
                     :map_id,
                     :solar_system_source_id,
                     :solar_system_target_id
                   ])

    drop_if_exists index(:map_chain_passages_v1, [:inserted_at])

    alter table(:user_activity_v1) do
      modify :user_id, :uuid, primary_key: true
    end
  end
end
