defmodule WandererApp.Repo.Migrations.AddZooFlags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_system_v1) do
      add :custom_flags, :text
    end
  end

  def down do
    alter table(:map_system_v1) do
      remove :custom_flags
    end
  end
end
