defmodule WandererApp.Repo.Migrations.AddUserTracking do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_v1) do
      add :primary_character_id,
          references(:character_v1,
            column: :id,
            name: "user_v1_primary_character_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:user_v1, "user_v1_primary_character_id_fkey")

    alter table(:user_v1) do
      remove :primary_character_id
    end
  end
end
