defmodule WandererApp.Repo.Migrations.RenameAllTheThings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:map_system_structures_v1), :type_id, to: :structure_type_id

    rename table(:map_system_structures_v1), :type, to: :structure_type

    rename table(:map_system_structures_v1), :owner, to: :owner_name

    alter table(:map_system_structures_v1) do
      modify :owner_name, :text
      modify :name, :text, null: false
      modify :structure_type, :text, null: false
      modify :structure_type_id, :text
    end
  end

  def down do
    alter table(:map_system_structures_v1) do
      modify :type_id, :text
      modify :type, :text, null: true
      modify :name, :text, null: true
      modify :owner, :text
      add :kind, :text
      add :group, :text
      add :custom_info, :text
      add :updated, :bigint
    end

    rename table(:map_system_structures_v1), :owner_name, to: :owner

    rename table(:map_system_structures_v1), :structure_type, to: :type

    rename table(:map_system_structures_v1), :structure_type_id, to: :type_id
  end
end
