defmodule WandererApp.Repo.Migrations.AddKeyToMapUserSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_user_settings_v1) do
      add :key, :text, null: false, default: "default"
    end

    drop_if_exists unique_index(:map_user_settings_v1, [:map_id, :user_id],
                     name: "map_user_settings_v1_uniq_map_user_index"
                   )

    create unique_index(:map_user_settings_v1, [:map_id, :user_id, :key],
             name: "map_user_settings_v1_uniq_map_user_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:map_user_settings_v1, [:map_id, :user_id, :key],
                     name: "map_user_settings_v1_uniq_map_user_key_index"
                   )

    create unique_index(:map_user_settings_v1, [:map_id, :user_id],
             name: "map_user_settings_v1_uniq_map_user_index"
           )

    alter table(:map_user_settings_v1) do
      remove :key
    end
  end
end
