defmodule WandererApp.Repo.Migrations.AddOwnerTicker do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("ALTER TABLE map_system_v1 ADD COLUMN IF NOT EXISTS owner_ticker text")
  end

  def down do
    execute("ALTER TABLE map_system_v1 DROP COLUMN IF EXISTS owner_ticker")
  end
end
