defmodule WandererApp.Repo.Migrations.FkUpdate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:map_template_v1, "map_template_v1_author_eve_id_fkey")

    alter table(:map_template_v1) do
      modify :author_eve_id, :text
    end

    create index(:map_template_v1, [:author_eve_id])
  end

  def down do
    drop_if_exists index(:map_template_v1, [:author_eve_id])

    alter table(:map_template_v1) do
      modify :author_eve_id,
             references(:character_v1,
               column: :eve_id,
               name: "map_template_v1_author_eve_id_fkey",
               type: :text,
               prefix: "public"
             )
    end
  end
end
