defmodule WandererApp.Repo.Migrations.UpdateSystemStructures do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:map_system_structures_v1), :description, to: :notes

    alter table(:map_system_structures_v1) do
      remove :custom_info
      remove :group
      remove :kind
      modify :notes, :text
    end
  end

  def down do
    alter table(:map_system_structures_v1) do
      modify :description, :text
      add :kind, :text
      add :group, :text
      add :custom_info, :text
    end

    rename table(:map_system_structures_v1), :notes, to: :description

  end
end
