defmodule WandererApp.Repo.Migrations.AddTemplates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:map_template_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :category, :text, null: false, default: "custom"
      add :author_eve_id, :text

      add :source_map_id,
          references(:maps_v1,
            column: :id,
            name: "map_template_v1_source_map_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :is_public, :boolean, null: false, default: false
      add :systems, {:array, :map}, null: false
      add :connections, {:array, :map}, null: false
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:map_template_v1, "map_template_v1_source_map_id_fkey")

    drop table(:map_template_v1)
  end
end
