defmodule WandererApp.Repo.Migrations.CreateMapDiscordWebhooks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:map_discord_webhooks_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :enabled?, :boolean, null: false, default: true
      add :last_delivery_at, :utc_datetime
      add :last_error, :text
      add :last_error_at, :utc_datetime
      add :consecutive_failures, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :notification_id,
          references(:map_discord_notifications_v1,
            column: :id,
            name: "map_discord_webhooks_v1_notification_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false

      add :encrypted_webhook_url, :binary, null: false
    end

    create unique_index(:map_discord_webhooks_v1, [:notification_id, :role],
             name: "map_discord_webhooks_v1_unique_notification_role_index"
           )
  end

  def down do
    drop_if_exists unique_index(:map_discord_webhooks_v1, [:notification_id, :role],
                     name: "map_discord_webhooks_v1_unique_notification_role_index"
                   )

    drop constraint(:map_discord_webhooks_v1, "map_discord_webhooks_v1_notification_id_fkey")

    drop table(:map_discord_webhooks_v1)
  end
end
