defmodule WandererApp.Repo.Migrations.AddWebhookMentionTargets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_discord_webhooks_v1) do
      add :mention_targets, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:map_discord_webhooks_v1) do
      remove :mention_targets
    end
  end
end
