defmodule WandererApp.Repo.Migrations.AddDiscordWebhookChannelInfo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_discord_webhooks_v1) do
      add :channel_id, :text
      add :channel_label, :text
    end
  end

  def down do
    alter table(:map_discord_webhooks_v1) do
      remove :channel_label
      remove :channel_id
    end
  end
end
