defmodule WandererApp.Repo.Migrations.SplitDiscordWebhooks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`

  Hand-edited: the generator's drop/add for `map_discord_notifications_v1` is
  unchanged, but a data-copy step has been inserted so existing rows aren't
  destroyed, and the four unrelated resources it also picked up (maps_v1,
  map_chain_v1, map_system_structures_v1, map_system_comments_v1 — stale
  `priv/resource_snapshots` drift, pre-existing and not part of this feature)
  have been removed from both `up/0` and `down/0`.
  """

  use Ecto.Migration

  def up do
    # Data step: give every existing notification a :system webhook carrying the
    # URL and failure state it used to hold itself.
    #
    # The ciphertext is copied verbatim, no decrypt/re-encrypt round trip.
    # AshCloak.do_encrypt/2 is
    #   value |> :erlang.term_to_binary() |> vault.encrypt!() |> Base.encode64()
    # (deps/ash_cloak/lib/ash_cloak.ex:65-73). The resource is used only to pick
    # a vault; neither the table nor the row identity enters the ciphertext, and
    # the vault's AES-GCM uses fixed AAD. The bytes therefore decrypt correctly
    # from the new table. Do not replace this with an application-level migration.
    #
    # `enabled?` is copied to BOTH rows. The old single flag conflated two
    # meanings — the user switching notifications off, and record_failure
    # auto-disabling after ten consecutive failures — and the migration cannot
    # tell them apart retroactively. Copying it down is the conservative
    # direction: a map that was silent before the upgrade stays silent after it,
    # and no webhook starts posting because a migration guessed generously. The
    # cost is that re-enabling a previously-disabled map also needs the
    # destination re-enabled. Do NOT "simplify" this to enabled? = true.
    # `"enabled?"` is double-quoted throughout: Postgres rejects `?` in an
    # unquoted identifier (the column is declared as `enabled?` because Ash
    # attribute names may end in `?`, but the underlying SQL identifier still
    # needs quoting outside of Ecto/Ash-generated DDL).
    # Guarded by `NOT EXISTS` against the child's real unique index
    # (`map_discord_webhooks_v1_unique_notification_role_index` on
    # `(notification_id, role)`): without it, any notification that already
    # has a `:system` child — a partially-applied deploy, a hand-repaired row,
    # or simply re-running this migration — aborts the whole statement on the
    # first collision instead of skipping the rows already split.
    #
    # Wrapped in a DO block (rather than a bare `execute`) so a notification
    # excluded by the guard can be *named* instead of silently losing its
    # `encrypted_webhook_url` when the column is dropped below. `up/0` runs
    # unattended during a deploy, so it must not abort here — skipping is the
    # correct, safe behavior, exactly as the guard already does — but it must
    # leave evidence in the deploy log. The skipped set is computed BEFORE the
    # INSERT (capturing exactly the rows the guard is about to exclude) and
    # reported via `RAISE WARNING` AFTER the INSERT has run, so what's printed
    # reflects the final, settled state rather than a snapshot that a
    # concurrent write could have invalidated. `RAISE WARNING` does not abort
    # the enclosing transaction — only `RAISE EXCEPTION` does.
    execute("""
    DO $$
    DECLARE
      already_split_ids text;
      already_split_count int;
    BEGIN
      SELECT string_agg(n.id::text, ', '), count(*)
      INTO already_split_ids, already_split_count
      FROM map_discord_notifications_v1 n
      WHERE n.encrypted_webhook_url IS NOT NULL
        AND EXISTS (
          SELECT 1 FROM map_discord_webhooks_v1 w
          WHERE w.notification_id = n.id AND w.role = 'system'
        );

      INSERT INTO map_discord_webhooks_v1 (
        id, notification_id, role, encrypted_webhook_url, "enabled?",
        last_delivery_at, last_error, last_error_at, consecutive_failures,
        inserted_at, updated_at
      )
      SELECT
        gen_random_uuid(), n.id, 'system', n.encrypted_webhook_url, n."enabled?",
        n.last_delivery_at, n.last_error, n.last_error_at, n.consecutive_failures,
        (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')
      FROM map_discord_notifications_v1 n
      WHERE NOT EXISTS (
        SELECT 1 FROM map_discord_webhooks_v1 w
        WHERE w.notification_id = n.id AND w.role = 'system'
      );

      IF already_split_count > 0 THEN
        RAISE WARNING 'split_discord_webhooks: % notification(s) already had a :system webhook; their parent encrypted_webhook_url was NOT migrated and is about to be dropped (ids: %)', already_split_count, already_split_ids;
      END IF;
    END $$;
    """)

    alter table(:map_discord_notifications_v1) do
      remove :encrypted_webhook_url
      remove :consecutive_failures
      remove :last_error_at
      remove :last_error
      remove :last_delivery_at
      add :focus_corp_ids, {:array, :bigint}, null: false, default: []
    end
  end

  def down do
    alter table(:map_discord_notifications_v1) do
      remove :focus_corp_ids
      add :last_delivery_at, :utc_datetime
      add :last_error, :text
      add :last_error_at, :utc_datetime
      add :consecutive_failures, :bigint, null: false, default: 0
      # 1. Restore the column WITHOUT the NOT NULL constraint. Codegen would
      #    have written `null: false` here (mirroring the resource's
      #    `allow_nil? false`); a NOT NULL column with no default added to a
      #    table that already has rows fails immediately, before the reverse
      #    copy below ever runs, aborting the rollback.
      add :encrypted_webhook_url, :binary, null: true
    end

    # 2. Copy each notification's :system destination back onto the parent.
    execute("""
    UPDATE map_discord_notifications_v1 n
    SET encrypted_webhook_url = w.encrypted_webhook_url,
        "enabled?" = w."enabled?",
        last_delivery_at = w.last_delivery_at,
        last_error = w.last_error,
        last_error_at = w.last_error_at,
        consecutive_failures = w.consecutive_failures
    FROM map_discord_webhooks_v1 w
    WHERE w.notification_id = n.id AND w.role = 'system'
    """)

    # 3. Delete the :system rows now that their data lives back on the parent.
    #    Without this, re-running `up/0` after a rollback (or rolling back
    #    twice) hits the child's unique (notification_id, role) identity: the
    #    old :system row is still there, so the INSERT in `up/0` collides with
    #    it. `:character` rows are untouched — they were never derived from the
    #    parent and have nowhere to roll back to.
    #    Scoped with a join to the parent table (rather than a bare
    #    `WHERE role = 'system'`) to match exactly the rows the UPDATE above
    #    just restored, not every `:system` row in the database.
    execute("""
    DELETE FROM map_discord_webhooks_v1 w
    USING map_discord_notifications_v1 n
    WHERE w.notification_id = n.id AND w.role = 'system'
    """)

    # 4. Only now can the original constraint be reinstated. A notification with
    #    no :system child would fail here — which is correct: it has no URL to
    #    roll back to, and silently leaving the column nullable would diverge
    #    from the pre-migration schema. Without the preflight below, that
    #    failure surfaces as Postgres' generic "column ... contains null
    #    values" error, which names neither the offending rows nor the fix.
    #    `down/0` is run by hand by an operator, so aborting here is correct —
    #    unlike `up/0` above, there is no unattended deploy to keep moving —
    #    but the abort must explain itself instead of leaving the operator to
    #    go spelunking.
    execute("""
    DO $$
    DECLARE
      unrestorable_ids text;
    BEGIN
      SELECT string_agg(id::text, ', ') INTO unrestorable_ids
      FROM map_discord_notifications_v1
      WHERE encrypted_webhook_url IS NULL;

      IF unrestorable_ids IS NOT NULL THEN
        RAISE EXCEPTION 'split_discord_webhooks rollback: notification(s) have no :system webhook to restore a webhook_url from (ids: %). Re-create a :system webhook for each, or delete these notification rows, then retry the rollback.', unrestorable_ids;
      END IF;
    END $$;
    """)

    execute(
      "ALTER TABLE map_discord_notifications_v1 ALTER COLUMN encrypted_webhook_url SET NOT NULL"
    )
  end
end
