defmodule WandererApp.Repo.Migrations.AddRouteAlertConfig do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_discord_notifications_v1) do
      add :route_alerts_enabled?, :boolean, null: false, default: false
      add :home_system_id, :bigint
      add :route_max_jumps, :bigint, null: false, default: 5
    end
  end

  def down do
    alter table(:map_discord_notifications_v1) do
      remove :route_max_jumps
      remove :home_system_id
      remove :route_alerts_enabled?
    end
  end
end
