defmodule WandererApp.Repo.Migrations.PersonalLocationApiTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maps_v1) do
      add :location_api_enabled, :boolean, null: false, default: false
    end

    alter table(:map_integration_tokens_v1) do
      modify :name, :text, null: true
      add :encrypted_value, :binary

      add :user_id,
          references(:user_v1,
            column: :id,
            name: "map_integration_tokens_v1_user_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          )
    end

    # Map-only hashes have no personal owner or recoverable ciphertext. Preserve
    # their history, but never allow them to become personal credentials.
    execute "UPDATE map_integration_tokens_v1 SET revoked_at = CURRENT_TIMESTAMP WHERE revoked_at IS NULL"

    create index(:map_integration_tokens_v1, [:user_id])

    create unique_index(:map_integration_tokens_v1, [:user_id, :map_id],
             name: "map_integration_tokens_v1_active_user_map_index",
             where: "(revoked_at IS NULL)"
           )

    create constraint(:map_integration_tokens_v1, :personal_credential,
             check: """
               revoked_at IS NOT NULL OR (user_id IS NOT NULL AND encrypted_value IS NOT NULL)
             """
           )
  end

  def down do
    # Downgrades must not turn personal credentials into shared map credentials.
    execute "UPDATE map_integration_tokens_v1 SET revoked_at = COALESCE(revoked_at, CURRENT_TIMESTAMP), name = COALESCE(name, 'Invalidated personal token')"

    drop_if_exists constraint(:map_integration_tokens_v1, :personal_credential)

    drop_if_exists unique_index(:map_integration_tokens_v1, [:user_id, :map_id],
                     name: "map_integration_tokens_v1_active_user_map_index"
                   )

    drop_if_exists index(:map_integration_tokens_v1, [:user_id])

    drop constraint(:map_integration_tokens_v1, "map_integration_tokens_v1_user_id_fkey")

    alter table(:map_integration_tokens_v1) do
      remove :user_id
      remove :encrypted_value
      modify :name, :text, null: false
    end

    alter table(:maps_v1) do
      remove :location_api_enabled
    end
  end
end
