defmodule WandererApp.Repo.Migrations.AddMapIntegrationTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:map_integration_tokens_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :scope, :text, null: false, default: "tracked_character_locations:read"
      add :digest, :binary, null: false
      add :generation, :bigint, null: false, default: 1
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :map_id,
          references(:maps_v1,
            column: :id,
            name: "map_integration_tokens_v1_map_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:map_integration_tokens_v1, "map_integration_tokens_v1_map_id_fkey")

    drop table(:map_integration_tokens_v1)
  end
end
