defmodule WandererApp.Repo.Migrations.AddWebhookGuildIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:map_discord_webhooks_v1) do
      add :guild_id, :text
      add :channel_label_source, :text
    end
  end

  def down do
    alter table(:map_discord_webhooks_v1) do
      remove :channel_label_source
      remove :guild_id
    end
  end
end
